export const GET_DONATIONS = 'GET_DONATIONS';
export const ADD_DONATION = 'ADD_DONATION';
export const DELETE_DONATION = 'DELETE_DONATION';
export const EDIT_DONATION = 'EDIT_DONATION';
export const COMPLETE_DONATION = 'COMPLETE_DONATION';
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED';
